version: 2
updates:
  - package-ecosystem: "uv"
    allow:
      - dependency-type: "direct"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dagster:
        patterns:
          - "dagster*"
